name: Deploy Shiny App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          install.packages('rsconnect')
          install.packages('shiny')
          install.packages('readxl')
          install.packages('dplyr')
          install.packages('ggplot2')
          install.packages('gridExtra')

      - name: Deploy to shinyapps.io
        env:
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        run: |
          library(rsconnect)
          rsconnect::setAccountInfo(name='your_shinyapps_username', token=Sys.getenv("SHINYAPPS_TOKEN"), secret=Sys.getenv("SHINYAPPS_SECRET"))
          rsconnect::deployApp(
            appDir = ".",  # Path to your app directory in the repository
            appName = "SleepDataAnalysisApp",
            account = "seanjibowu"
          )
